# Generated by Django 4.2.2 on 2023-06-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.AutoField(primary_key=True, serialize=False)),
                ('python', models.FloatField(max_length=200)),
            ],
        ),
    ]
