# Generated by Django 4.2.2 on 2023-06-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tableau', models.FloatField()),
                ('sql', models.FloatField()),
                ('r', models.FloatField()),
                ('python', models.FloatField()),
                ('big_data', models.FloatField()),
                ('spss', models.FloatField()),
                ('data_cleaning', models.FloatField()),
                ('data_visualization', models.FloatField()),
                ('modeling', models.FloatField()),
                ('programming', models.FloatField()),
                ('technical_average', models.FloatField()),
                ('communication', models.FloatField()),
                ('problem_solving', models.FloatField()),
                ('critical_thinking', models.FloatField()),
                ('leadership', models.FloatField()),
                ('soft_average', models.FloatField()),
                ('bootcamp_id', models.IntegerField()),
            ],
        ),
    ]
