# Generated by Django 4.2.2 on 2023-06-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='big_data',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='communication',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='critical_thinking',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='data_cleaning',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='data_visualization',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='leadership',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='modeling',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='problem_solving',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='programming',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='python',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='r',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='soft_average',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='spss',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='sql',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='tableau',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='technical_average',
            field=models.FloatField(default=0),
        ),
    ]
