# Generated by Django 4.2.2 on 2023-06-08 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_student_big_data_alter_student_communication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('bootcamp_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='bootcamp_id',
        ),
        migrations.AddField(
            model_name='student',
            name='bootcamp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.bootcamp'),
            preserve_default=False,
        ),
    ]
