# Generated by Django 4.2.2 on 2023-06-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_bootcamp_remove_student_bootcamp_id_student_bootcamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bootcamp',
        ),
        migrations.DeleteModel(
            name='Bootcamp',
        ),
    ]
