# Generated by Django 4.2.2 on 2023-06-08 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_student_bootcamp_delete_bootcamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('bootcamp_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='bootcamp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.bootcamp'),
            preserve_default=False,
        ),
    ]
